app:
  name: web-app
  image:
    repository: tiangolo/uwsgi-nginx-flask
    tag: "python3.9"
    pullPolicy: Always
  port: 80
  replicas: 2

mysql:
  image: mysql:8.0
  rootPassword: "password"
  database: "itemsdb"
  port: 3306
  storage: 1Gi

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
